export const positionsObject = {
	sixtyNine: false,
	analGet: false,
	analGive: false,
	doggyGet: false,
	doggyGive: false,
	handGive: false,
	handGet: false,
	kink: false,
	missionary: false,
	oralGet: false,
	spank: false,
	spoon: false,
	topsit: false,
	toys: false,
	addPosition: false,
};

export const positionsText = {
	sixtyNine: '69',
	addPosition: 'Add New Position',
	analGet: 'Anal Receive',
	analGive: 'Anal Give',
	doggyGet: 'Doggy Receive',
	doggyGive: 'Doggy Give',
	handGive: 'Hand Receive',
	handGet: 'Hand Get',
	kink: 'Kink',
	missionary: 'Missionary',
	oralGet: 'Oral Receive',
	spank: 'Spanking',
	spoon: 'Spoon',
	topsit: 'Top Sit',
	toys: 'Toys'
};
